<a href="https://colab.research.google.com/github/PersonaOut/C126_Curso-de-Introducci-n-a-Machine-Learning/blob/main/03_Representando_datasets_con_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd

# Representar Datos con Tensores

---






In [ ]:
numpyArray = np.random.rand(2,2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[0.5960, 0.6585],
        [0.0380, 0.4631]], dtype=torch.float64)

Obtener Media

In [ ]:
print(from_numpy)
#Con el metodo mean obtienes la media del tensor en total
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0)) # con dim=0 obtienes la media de la columna
print(torch.mean(from_numpy, dim=1)) # con dim = 1 obtienes la media de la fila
#ademas si agregas como parametro dim = n obtiene la media de una fila o columna

tensor([[0.5960, 0.6585],
        [0.0380, 0.4631]], dtype=torch.float64)
tensor(0.4389, dtype=torch.float64)
tensor([0.3170, 0.5608], dtype=torch.float64)
tensor([0.6273, 0.2506], dtype=torch.float64)


Obtener Desviacion standart



In [ ]:
torch.std(from_numpy, dim=1)

tensor([0.0442, 0.3006], dtype=torch.float64)

In [ ]:
#Es posible guardar los tensores con el metodo save(tensor, 'Archivo.t')
torch.save(from_numpy, 'tensor.t')

In [ ]:
#A la vez que se puede guardar es posible cargar
load = torch.load('tensor.t')
load

tensor([[-1.2472, -1.0963],
        [ 1.1256,  0.2792]], dtype=torch.float64)

In [ ]:
ur1 = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
df = pd.read_csv(ur1)
df

Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31   
1               1   20801   Cristiano Ronaldo   33   
2               2  190871           Neymar Jr   26   
3               3  193080              De Gea   27   
4               4  192985        K. De Bruyne   27   
...           ...     ...                 ...  ...   
18202       18202  238813        J. Lundstram   19   
18203       18203  243165  N. Christoffersson   19   
18204       18204  241638           B. Worman   16   
18205       18205  246268      D. Walker-Rice   17   
18206       18206  246269           G. Nugent   16   

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium   
...                                               ...         ...   
18202  https://cdn.sofifa.org/players/4/19/238813.png     England   
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden   
18204  https://cdn.sofifa.org/players/4/19/241638.png     England   
18205  https://cdn.sofifa.org/players/4/19/246268.png     England   
18206  https://cdn.sofifa.org/players/4/19/246269.png     England   

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png       94         94   
1      https://cdn.sofifa.org/flags/38.png       94         94   
2      https://cdn.sofifa.org/flags/54.png       92         93   
3      https://cdn.sofifa.org/flags/45.png       91         93   
4       https://cdn.sofifa.org/flags/7.png       91         92   
...                                    ...      ...        ...   
18202  https://cdn.sofifa.org/flags/14.png       47         65   
18203  https://cdn.sofifa.org/flags/46.png       47         63   
18204  https://cdn.sofifa.org/flags/14.png       47         67   
18205  https://cdn.sofifa.org/flags/14.png       47         66   
18206  https://cdn.sofifa.org/flags/14.png       46         66   

                      Club  ... Composure Marking StandingTackle  \
0             FC Barcelona  ...      96.0    33.0           28.0   
1                 Juventus  ...      95.0    28.0           31.0   
2      Paris Saint-Germain  ...      94.0    27.0           24.0   
3        Manchester United  ...      68.0    15.0           21.0   
4          Manchester City  ...      88.0    68.0           58.0   
...                    ...  ...       ...     ...            ...   
18202      Crewe Alexandra  ...      45.0    40.0           48.0   
18203       Trelleborgs FF  ...      42.0    22.0           15.0   
18204     Cambridge United  ...      41.0    32.0           13.0   
18205      Tranmere Rovers  ...      46.0    20.0           25.0   
18206      Tranmere Rovers  ...      43.0    40.0           43.0   

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning  \
0               26.0      6.0        11.0       15.0           14.0   
1               23.0      7.0        11.0       15.0           14.0   
2               33.0      9.0         9.0       15.0           15.0   
3               13.0     90.0        85.0       87.0           88.0   
4               51.0     15.0        13.0        5.0           10.0   
...              ...      ...         ...        ...            ...   
18202           47.0     10.0        13.0        7.0            8.0   
18203           19.0     10.0         9.0        9.0            5.0   
18204           11.0      6.0         5.0       10.0            6.0   
18205           27.0     14.0         6.0       14.0            8.0   
18206           50.0     10.0        15.0        9.0           12.0   

      GKReflexes Release Clause  
0            8.0        €226.5M 

In [ ]:
df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [ ]:
subset = df[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis=0, how="any")
#Borramos los datos vacios
subset, subset.shape

(       Overall  Age  International Reputation  Weak Foot  Skill Moves
 0           94   31                       5.0        4.0          4.0
 1           94   33                       5.0        4.0          5.0
 2           92   26                       5.0        5.0          5.0
 3           91   27                       4.0        3.0          1.0
 4           91   27                       4.0        5.0          4.0
 ...        ...  ...                       ...        ...          ...
 18202       47   19                       1.0        2.0          2.0
 18203       47   19                       1.0        2.0          2.0
 18204       47   16                       1.0        3.0          2.0
 18205       47   17                       1.0        3.0          2.0
 18206       46   16                       1.0        3.0          2.0
 
 [18159 rows x 5 columns],
 (18159, 5))

In [ ]:
columns = subset.columns[1:]
#De esta forma guardamos en un array el nombre de las columnas del 1 hacia adelante
players = torch.tensor(subset.values).float()
#subset.values obtiene los valores del subset y casteo a flotente
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [ ]:
data = players[:, 1:]
#elijo de todo el dataset los de la columna 1 en adelante
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]),
 torch.Size([18159, 4]))

In [ ]:
target = players[:,0]
#selecciono de toda la particion del dataframe la primera columna
target , target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [ ]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [ ]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [ ]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [ ]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notsoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notsoGoodMean = torch.mean(notsoGood, dim=0)

#goodMean, averageMean, notsoGoodMean

for i, args in enumerate(zip(columns, goodMean, averageMean, notsoGoodMean)):
  print("{:25} {:6.2f} {:6.2f} {:6.2f}".format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22


En la librería Torch de Python, los comandos .ge(), .gt(), .lt() y .le() se utilizan para realizar comparaciones elemento
 a elemento en tensores y devolver tensores booleanos como resultado.

-.ge() significa "greater than or equal to" (mayor o igual que). Devuelve un tensor booleano con True en los elementos donde el tensor original sea mayor o igual que el valor de comparación especificado, y False en los demás elementos.

-.gt() significa "greater than" (mayor que). Devuelve un tensor booleano con True en los elementos donde el tensor original sea estrictamente mayor que el valor de comparación especificado, y False en los demás elementos.

-.lt() significa "less than" (menor que). Devuelve un tensor booleano con True en los elementos donde el tensor original sea estrictamente menor que el valor de comparación especificado, y False en los demás elementos.

-.le() significa "less than or equal to" (menor o igual que). Devuelve un tensor booleano con True en los elementos donde el tensor original sea menor o igual que el valor de comparación especificado, y False en los demás elementos.

In [ ]:
#Ejemplo
print(torch.ge(target, 85))

tensor([ True,  True,  True,  ..., False, False, False])
