In [ ]:
import torch
import numpy as np
import pandas as pd

In [ ]:
torch.__version__

'2.0.0+cu118'

In [ ]:
tensor_a = torch.ones(2,2)
#El metodo ones(f,c) crea un tensor con 1 como elementos

In [ ]:
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
tensor_b = torch.Tensor(2, 2)
#El metodo Tensor(f,c) crea un tensor con numeros aleatorios
print(tensor_b)
tensor_b.uniform_(0, 1)
#El metodo uniform() genera valores aleatorios en un rango de valores

tensor([[1.8295e+15, 4.5622e-41],
        [1.2613e-34, 0.0000e+00]])


tensor([[0.1642, 0.9457],
        [0.6616, 0.1189]])

In [ ]:
tensor_c = torch.rand(2, 2)
#metodo rand de torch genera devuelve un tensor con valores aleatorios
tensor_c

tensor([[0.5965, 0.7348],
        [0.7870, 0.7127]])

In [ ]:
result = tensor_b + tensor_c
result

tensor([[0.7607, 1.6805],
        [1.4487, 0.8315]])

In [ ]:
result.shape
#el metodo shape nos muestra el tamaño del tensor

reshaped = result.view(1,4)
#el metodo view(f,c) modifica la dimension del tensor sin modificar los datos subyacente
reshaped
# or reshaped = result.view(4,1)

tensor([[0.7607, 1.6805, 1.4487, 0.8315]])

In [ ]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
#modificar un elemento del tensor
print(points)
points.storage()
#el metodo .storage() devuelve una estructura unidimencional con los elementos del tensor para su modificar

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


<ipython-input-23-6dff70337007>:6: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()
/usr/local/lib/python3.10/dist-packages/IPython/lib/pretty.py:700: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/usr/local/lib/python3.10/dist-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly

 1.0
 2.5
 3.0
 4.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]

In [ ]:
p_t = points.t()
#el metodo .t() devuelve la traspuesta del tensor
p_t, p_t.stride()
#El metodo stride() nos muestran la cantidad de desplazamientos un elemento a otro

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]),
 (1, 2))

In [ ]:
tensor_x = torch.tensor([1,2,3,4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x , torch.unsqueeze(tensor_x, 1)
#el metodo unsqueeze(tensor, D) modifica la dimension del tensor y puede agregar dimensiones adicionales

(tensor([1, 2, 3, 4]),
 tensor([[1],
         [2],
         [3],
         [4]]))

In [ ]:
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)
#con el metodo .from_numpy(array) es posible convertir una matriz de numpy a un tensor